// utils/seedData.js — CampusConnect
// Demo data seeded on first app launch

import { getUsers, saveUsers, getItems, saveItems, getNotifications, saveNotifications, markSeeded } from './localStorage.js';

const DEMO_USER_ID = 'demo-user-001';
const DEMO_USER2_ID = 'demo-user-002';
const DEMO_USER3_ID = 'demo-user-003';

export const seedDemoData = () => {
  // Seed users
  const demoUsers = [
    {
      id: DEMO_USER_ID,
      name: 'Arjun Sharma',
      email: 'arjun@campus.edu',
      password: 'demo123',
      department: 'Computer Science & Engineering',
      year: '3rd Year',
      phone: '9876543210',
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    },
    {
      id: DEMO_USER2_ID,
      name: 'Priya Patel',
      email: 'priya@campus.edu',
      password: 'demo123',
      department: 'Information Technology',
      year: '2nd Year',
      phone: '9876543211',
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    },
    {
      id: DEMO_USER3_ID,
      name: 'Rohan Verma',
      email: 'rohan@campus.edu',
      password: 'demo123',
      department: 'Electronics & Communication',
      year: '4th Year',
      phone: '9876543212',
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    },
  ];

  const existingUsers = getUsers();
  const demoIds = demoUsers.map(u => u.id);
  const filtered = existingUsers.filter(u => !demoIds.includes(u.id));
  saveUsers([...filtered, ...demoUsers]);

  // Seed items
  const demoItems = [
    {
      id: 'item-001',
      title: 'Apple AirPods Pro',
      type: 'lost',
      category: 'electronics',
      description: 'Lost my white AirPods Pro with a transparent case. Has a small scratch on the left pod. Last seen near the library entrance.',
      location: 'Library',
      date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
      contactInfo: '9876543210',
      images: [],
      reportedBy: DEMO_USER_ID,
      reportedByName: 'Arjun Sharma',
      resolved: false,
      claimedBy: null,
      claimRequests: [],
      comments: [],
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'item-002',
      title: 'Student ID Card',
      type: 'found',
      category: 'documents',
      description: 'Found a student ID card near the cafeteria. Belongs to someone from CSE dept. Please claim at the admin block.',
      location: 'Cafeteria',
      date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
      contactInfo: '9876543211',
      images: [],
      reportedBy: DEMO_USER2_ID,
      reportedByName: 'Priya Patel',
      resolved: false,
      claimedBy: null,
      claimRequests: [],
      comments: [],
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'item-003',
      title: 'Blue Denim Jacket',
      type: 'lost',
      category: 'clothing',
      description: 'Lost a blue denim jacket during the seminar. It has my name written inside — "Rohan V". Medium size.',
      location: 'Seminar Hall',
      date: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
      contactInfo: '9876543212',
      images: [],
      reportedBy: DEMO_USER3_ID,
      reportedByName: 'Rohan Verma',
      resolved: false,
      claimedBy: null,
      claimRequests: [],
      comments: [],
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: 'item-004',
      title: 'Set of 3 Keys with Keychain',
      type: 'found',
      category: 'keys',
      description: 'Found a set of keys with a red keychain near Block A. Has 3 keys. Contact to claim.',
      location: 'Block A',
      date: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
      contactInfo: '9876543210',
      images: [],
      reportedBy: DEMO_USER_ID,
      reportedByName: 'Arjun Sharma',
      resolved: false,
      claimedBy: null,
      claimRequests: [],
      comments: [],
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      id: 'item-005',
      title: 'Data Structures Textbook',
      type: 'lost',
      category: 'books',
      description: 'Lost my "Introduction to Algorithms" (CLRS) textbook. It has yellow highlights and my handwritten notes in the margins.',
      location: 'Lab 1',
      date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
      contactInfo: '9876543211',
      images: [],
      reportedBy: DEMO_USER2_ID,
      reportedByName: 'Priya Patel',
      resolved: false,
      claimedBy: null,
      claimRequests: [],
      comments: [],
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      id: 'item-006',
      title: 'Black Backpack',
      type: 'found',
      category: 'bags',
      description: 'Found a black Wildcraft backpack near the parking area. Contains some notebooks and a water bottle. Please claim with proof.',
      location: 'Parking Area',
      date: new Date(Date.now() - 6 * 86400000).toISOString().split('T')[0],
      contactInfo: '9876543212',
      images: [],
      reportedBy: DEMO_USER3_ID,
      reportedByName: 'Rohan Verma',
      resolved: false,
      claimedBy: null,
      claimRequests: [],
      comments: [],
      createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    },
    {
      id: 'item-007',
      title: 'Silver Watch',
      type: 'lost',
      category: 'accessories',
      description: 'Lost a silver-colored Casio watch near the sports ground. Sentimental value. Reward for return.',
      location: 'Sports Ground',
      date: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
      contactInfo: '9876543210',
      images: [],
      reportedBy: DEMO_USER_ID,
      reportedByName: 'Arjun Sharma',
      resolved: true,
      claimedBy: DEMO_USER2_ID,
      claimRequests: [],
      comments: [],
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'item-008',
      title: 'Bluetooth Earphones',
      type: 'found',
      category: 'electronics',
      description: 'Found boAt Airdopes earphones near Block B staircase. Still in good condition. Please describe the model to claim.',
      location: 'Block B',
      date: new Date(Date.now() - 8 * 86400000).toISOString().split('T')[0],
      contactInfo: '9876543211',
      images: [],
      reportedBy: DEMO_USER2_ID,
      reportedByName: 'Priya Patel',
      resolved: false,
      claimedBy: null,
      claimRequests: [],
      comments: [],
      createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    },
    {
      id: 'item-009',
      title: 'Prescription Glasses',
      type: 'lost',
      category: 'accessories',
      description: 'Lost prescription glasses with a black frame. Power: -2.5 (both eyes). Left near the seminar hall chairs.',
      location: 'Seminar Hall',
      date: new Date(Date.now() - 9 * 86400000).toISOString().split('T')[0],
      contactInfo: '9876543212',
      images: [],
      reportedBy: DEMO_USER3_ID,
      reportedByName: 'Rohan Verma',
      resolved: false,
      claimedBy: null,
      claimRequests: [],
      comments: [],
      createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    },
    {
      id: 'item-010',
      title: 'USB-C Charging Cable',
      type: 'found',
      category: 'electronics',
      description: 'Found a branded (Anker) braided USB-C cable in the library. Deposited at the admin block helpdesk.',
      location: 'Library',
      date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
      contactInfo: '9876543210',
      images: [],
      reportedBy: DEMO_USER_ID,
      reportedByName: 'Arjun Sharma',
      resolved: false,
      claimedBy: null,
      claimRequests: [],
      comments: [],
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
    {
      id: 'item-011',
      title: 'Brown Leather Wallet',
      type: 'lost',
      category: 'bags',
      description: 'Lost a brown leather wallet. Contains some cash, student ID, and an ATM card. Please return if found, reward assured.',
      location: 'Cafeteria',
      date: new Date(Date.now() - 11 * 86400000).toISOString().split('T')[0],
      contactInfo: '9876543211',
      images: [],
      reportedBy: DEMO_USER2_ID,
      reportedByName: 'Priya Patel',
      resolved: false,
      claimedBy: null,
      claimRequests: [],
      comments: [],
      createdAt: new Date(Date.now() - 11 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    },
    {
      id: 'item-012',
      title: 'Cricket Bat',
      type: 'found',
      category: 'sports',
      description: 'Found a Ceat cricket bat near the sports ground storeroom. Has stickers on the back. Please claim with proof of ownership.',
      location: 'Sports Ground',
      date: new Date(Date.now() - 12 * 86400000).toISOString().split('T')[0],
      contactInfo: '9876543212',
      images: [],
      reportedBy: DEMO_USER3_ID,
      reportedByName: 'Rohan Verma',
      resolved: false,
      claimedBy: null,
      claimRequests: [],
      comments: [],
      createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    },
  ];

  const existingItems = getItems();
  const demoItemIds = demoItems.map(i => i.id);
  const filteredItems = existingItems.filter(i => !demoItemIds.includes(i.id));
  saveItems([...filteredItems, ...demoItems]);

  // Seed demo notifications
  const demoNotifications = [
    {
      id: 'notif-001',
      type: 'claim',
      message: 'Priya Patel sent a claim request for your item "Apple AirPods Pro"',
      itemId: 'item-001',
      itemTitle: 'Apple AirPods Pro',
      fromUser: DEMO_USER2_ID,
      fromUserName: 'Priya Patel',
      toUser: DEMO_USER_ID,
      read: false,
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'notif-002',
      type: 'system',
      message: 'Welcome to CampusConnect! Start by reporting a lost or found item.',
      itemId: null,
      fromUser: null,
      fromUserName: 'CampusConnect',
      toUser: DEMO_USER_ID,
      read: false,
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
  ];

  const existingNotifs = getNotifications();
  const demoNotifIds = demoNotifications.map(n => n.id);
  const filteredNotifs = existingNotifs.filter(n => !demoNotifIds.includes(n.id));
  saveNotifications([...filteredNotifs, ...demoNotifications]);
  markSeeded();
};
